sudo: true

language: java

jdk:
- oraclejdk8

services:
- mongodb

script:
- mvn clean install

env:
  - "TEST_CROUP=1"
  - "TEST_CROUP=2"
  global:
    - CI_NODE_TOTAL=2
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
