sudo: false
language: java
jdk:
- oraclejdk8
services:
- mongodb
script:
- bin/run.sh
env:
  global:
    - CI_NODE_TOTAL=4
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
